keys:
  - &admin_oxa DD0998E6CDF294537FC604F991FA5E5BF9AA901C
  # hosts
  - &toaster age1avaphjah4k8n80jrnraeqh9r94fu6awd6k37z4zfjssl5ft07qkqmuehcm
  - &cloud age1j3xpuuqaph5z885er90mftfsu6g3hw4q469k37a3veqktwntzdpqgue4z5
  - &minime age1chq5k0t38882rtyljez8cwmvtcstu4tafzvveuhjrujvsqk72f9s9guc06
  # microvms
  - &auth age1vzwz5s35w9g8ck9l5zaq5skrnl3mqzf3hsnc9w22sj4k8tu8kqfstpg2a8
  - &radicale age1j6z39kmnxkqa7jdcjsydy5cryjce7fttf225fh3pldyvq06ax3fq58mk8c
creation_rules:
  - path_regex: secrets/toaster/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *toaster
  - path_regex: secrets/cloud/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *cloud
  - path_regex: secrets/minime/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *minime
  - path_regex: secrets/auth/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *auth
  - path_regex: secrets/radicale/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *radicale
