keys:
  - &admin_oxa DD0998E6CDF294537FC604F991FA5E5BF9AA901C
  - &microwave age1eysr2m8ust6gq9jk88lpzzcy8gdrzlts69zlfqul766t6gvqw9qq24z68l
  - &cirrus age1qm70jkg7us4ft4x3nh7kwxlul022kteescjj83ywvjhysj6nsq5sw7l6p8
creation_rules:
  - path_regex: secrets/microwave/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *microwave
  - path_regex: secrets/cirrus/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *cirrus
