keys:
  - &admin_oxa DD0998E6CDF294537FC604F991FA5E5BF9AA901C
  - &microwave age18t2dc53m7a53996fwcmuanwjtxxvvgkntpmdvd3q42pnkch6rajqnm4up8
  - &cirrus age1qm70jkg7us4ft4x3nh7kwxlul022kteescjj83ywvjhysj6nsq5sw7l6p8
  - &dishwasher age1cxlskqynwl5njjm0qf363308dsjwxjq59rq7pn6ucpscpzpvry4qwtpx73
  - &nextcloud age1ds7zgenz9a664jqx5308m6q5mgtavzmelg239xsj8mdh64pmqa9qtkffmk
  - &toaster age1qyj95tsntreefqeetawqy5pf26456s9c0v3tzz8yzs706c0jsg6qv56jzk
  - &music age1qyj95tsntreefqeetawqy5pf26456s9c0v3tzz8yzs706c0jsg6qv56jzk
creation_rules:
  - path_regex: secrets/microwave/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *microwave
  - path_regex: secrets/cirrus/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *cirrus
  - path_regex: secrets/dishwasher/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *dishwasher
  - path_regex: secrets/nextcloud/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *nextcloud
  - path_regex: secrets/toaster/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *toaster
  - path_regex: secrets/music/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *music
