keys:
  - &admin_oxa DD0998E6CDF294537FC604F991FA5E5BF9AA901C
  - &toaster age1qyj95tsntreefqeetawqy5pf26456s9c0v3tzz8yzs706c0jsg6qv56jzk
creation_rules:
  - path_regex: secrets/toaster/[^/]+\.yaml$
    key_groups:
      - pgp:
        - *admin_oxa
        age:
        - *toaster
